---
title: "Stage keuze"
author: "Fatima Danawar"
date: "2023-11-21"
output: html_document
---

#Eerste keuze:
##Bedrijfnaam: Genmab in Utrecht
###Ondezoek bij afdeling Bioanalytical Science naar de ontwikkeling van methodes om de medicijn kandidaten van Genmab in patienten te kunnen meten.Hiervoor laten wij moleculen ontwikkelen die onze kandidaten kunnen binden (assaytools). Wij hebben assaytools ontwikkeld die onze kandidaten in verschillende hoedanigheid kunnen meten. Dit is een nieuwe benadering die mogelijk veel inzicht in onze klinische studies kan opleveren. Wij willen nu met deze moleculen kijken of onze theoretische aannames m.b.t. specificiteit en toepasbaarheid in bioanalyse kloppen. De stage zal dan ook gericht zijn op het ontwikkelen van verschillende methodes met deze nieuwe assay tools. En de haalbaarheid en toepasbaarheid in de klinische assays te bepalen. Je zal tijdens deze stage met name ligand binding assays (bijv Elisa) gaan toepassen. Je zal methodes vanaf het begin gaan ontwikkelen, wat je inzicht zal gaan geven in het proces van methode ontwikkeling alsmede hoe dit te documenteren. Ook zal je expertise opbouwen in het labelen van de moleculen met verschillende detectie moleculen.

#Tweede Keuze:
##Bedrijfnaam: Hubrecht institute in Utrecht
###Organoids in fertility research: Stage bij de voorplantingsgeneeskunde in het UMC Utrecht. De labs bevinden zich binnen het RMCU (Hubrecht instituut) waar verschillende groepen die met organoids werken met elkaar samenwerken. Tijdens deze stage zul je leren werken met endometriale organoids en stromale fibroblasten. Wij gebruiken verschillende technieken om uit te lezen hoe deze cellen (in enkele cultuur of als co-kweek) reageren op externe factoren zoals seminal plasma of het microbioom. Wij gebruiken onder andere QPCR, viablility assays en immunofluorescentie microscopie (confocal/Thunder) hiervoor. Er zijn binnen onze groep verschillende projecten die lopen dus afhankelijk van de interesse van de student kan in overleg de stage worden ingevuld. 
###Specifieke vaardigheidseisen: ervaring met moleculaire technieken en celkweek, hoge motivatie, zelfstandig, geïnteresseerd in het vrouwelijke voortplantingssysteem en translationeel onderzoek

#Derde keuze:
##Bedrijfnaam: Silycs, Synaptologics BV in Bilthoven
###Onderzoek naar neurodegeneratieve ziekten; histologie & pathologie bij muizenhersenen.
###Het bedrijf Sylics is een contract research organisatie (CRO) dat neurowetenschappelijk onderzoek uitvoert voor academische labs en klanten in de biofarmaceutische industrie. Onze projecten zijn afhankelijk van de vraag van klanten op dat moment, maar over het algemeen zijn dit in vivo studies in muismodellen van neurodegeneratieve ziekten (Alzheimer’s, Parkinson’s, ALS), zeldzame genetische aandoeningen en psychiatrische ziektes.

###In het kader van deze experimenten doen wij veel histologische kleuringen om de pathologie in de hersenen van de muizen te onderzoeken. Wij zijn regelmatig op zoek naar studenten die het leuk vinden om alles over histologie te leren. Over het algemeen richten dit soort stageprojecten zich op het karakteriseren van een specifiek muismodel van een neurodegeneratieve ziekte. Wij kijken dan bijvoorbeeld op verschillende tijdpunten naar de pathologie en neuroinflammatie in muismodellen van de ziekte van Alzheimer of Parkinson.

###Een stage bij Sylics vooral bestaan uit de volgende activiteiten:
-Snijden van hersencoupes met een cryo-microtoom.
-Kleuren van de coupes met histologische 'chemische' stains of fluorescente antilichamen.
-Opzetten en optimaliseren van kleuringen die niet (meteen) werken.
-Widefield en fluorescentiemicroscopie.
-Image analyse van 'gefotografeerde' stainings (quantificatie)
-Statistische analyse van de resultaten.
-Presenteren van de (interim) resultaten aan de rest van het team.
-Overdragen van opgedane kennis in het lab aan collega's binnen Sylics.
-Het schrijven van een verslag over de theoretische achtergrond en resultaten

